version: "3.4"

services:

  tdata1:
    image: "ghcr.io/sergey55511/data1:dev"
    container_name: tdata1
    ports:
      - "3000:3000"
    env_file:
      - ./docker/app.global.env

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
