export const data = [
    { id: 1, state: 'Мытый', active: true },
    { id: 2, state: 'Сортированный', active: true },
    { id: 3, state: 'Клееный', active: true },
    { id: 4, state: 'Насыщенный', active: true },
    { id: 5, state: 'Автоклавированый', active: true },
    { id: 6, state: 'Шлифованный гровером', active: true },
    { id: 7, state: 'Обкусанный', active: true },
    { id: 8, state: 'Обточенный', active: true },
    { id: 9, state: 'Калиброванный', active: true },
    { id: 10, state: 'Докалиброванный', active: true },
    { id: 11, state: 'Шлифованный ШД', active: true },
    { id: 12, state: 'Полированный', active: true },
    { id: 13, state: 'Распиленный', active: true },
    { id: 14, state: 'Сырец', active: true },
    { id: 15, state: 'Сортированный насыщенный', active: true },
    { id: 16, state: 'Сортированный автоклав', active: true },
    { id: 17, state: 'Клеенная заготовка', active: true },
    { id: 18, state: 'Калиброванный ИК', active: true },
    { id: 19, state: 'Сортированная заготовка', active: true },
    { id: 20, state: 'Сортированный по длине', active: true },
    { id: 21, state: 'Распиленная заготовка', active: true },
    { id: 22, state: 'Сверленная таблетка', active: true },
    { id: 23, state: 'Сверленый', active: true },
    { id: 24, state: 'Шлифованная заготовка', active: true },
    { id: 25, state: 'Сверленый водой', active: true },
    { id: 26, state: 'Галтованный (грубо)', active: true },
    { id: 27, state: 'Термообр-ный (лампы)', active: true },
    { id: 28, state: 'Термообр-ный (печь)', active: true },
    { id: 29, state: 'Полированный', active: true },
    { id: 30, state: 'Сортированный элемент', active: true },
    { id: 31, state: 'Шлифованный дакат', active: true },
    { id: 32, state: 'Готовый элемент мин.группы', active: true },
    { id: 33, state: 'Сортированные обрезки', active: true },
    { id: 34, state: 'Смешанный', active: true },
    { id: 35, state: 'Готовое изделие', active: true },
    { id: 36, state: 'Разобранный', active: true },
    { id: 37, state: 'Обрезки', active: true },
    { id: 38, state: 'Шлифованный МШ', active: true },
    { id: 39, state: 'Калиброванный МШ', active: true },
    { id: 40, state: 'Клеенный 2', active: true },
    { id: 41, state: 'Мытый 2', active: true },
    { id: 42, state: 'Галтованный', active: true },
    { id: 43, state: 'Прессованный', active: true },
];
