export const KEYSLEFTOVERS = {
    pp: { key: 'pp', title: 'ПП' },
    date: { key: 'date', title: 'Дата' },
    user: { key: 'userLogin', title: 'Выдал' },
    store: { key: 'store', title: 'Выдал' },
    manager: { key: 'managerLogin', title: 'Исполнитель' },
    operation: { key: 'operation', title: 'Операция' },
    workpieceType: { key: 'workpieceType', title: 'Тип заготовки' },
    fullModel: { key: 'fullModel', title: 'Модель' },
    numDocument: { key: 'numDocument', title: 'Номер документа' },
    model: { key: 'model', title: 'Модель' },
    type: { key: 'type', title: 'Тип' },
    sizeRange: { key: 'sizeRange', title: 'Размерный ряд' },
    fraction: { key: 'fraction', title: 'Фракция' },
    materialGroup: { key: 'materialGroup', title: 'Группа сырья' },
    color: { key: 'color', title: 'Цвет' },
    length: { key: 'length', title: 'Длина' },
    channel: { key: 'channel', title: 'Канал' },
    grade: { key: 'grade', title: 'Сорт' },
    state: { key: 'state', title: 'Состояние' },
    lot: { key: 'lot', title: 'Партия' },
    productionId: { key: 'productionId', title: '№ Производства' },
    production: { key: 'production', title: 'Производство' },
    numProduction: { key: 'numProduction', title: '№ производства' },
    width: { key: 'width', title: 'Остаток гр.' },
    count: { key: 'count', title: 'Остаток шт.' },
    widthOut: { key: 'widthOut', title: 'Отгрузка гр.' },
    countItemsOut: { key: 'countItemsOut', title: 'Отгрузка шт.' },
    code: { key: 'code', title: '' },
    defect: { key: 'defect', title: '' },
};
