export const KEYSLEFTOVERS = {
    pp: { key: 'pp', title: 'ПП' },
    user: { key: 'userLogin', title: 'Выдал' },
    manager: { key: 'managerLogin', title: 'Исполнитель' },
    operation: { key: 'operation', title: 'Операция' },
    workpieceType: { key: 'workpieceType', title: 'Тип заготовки' },
    model: { key: 'model', title: 'Модель' },
    sizeRange: { key: 'sizeRange', title: 'Размерный ряд' },
    materialGroup: { key: 'materialGroup', title: 'Группа сырья' },
    color: { key: 'color', title: 'Цвет' },
    length: { key: 'length', title: 'Длина' },
    channel: { key: 'channel', title: 'Канал' },
    grade: { key: 'grade', title: 'Сорт' },
    state: { key: 'state', title: 'Состояние' },
    lot: { key: 'lot', title: 'Партия' },
    productionId: { key: 'productionId', title: '№ Производства' },
    production: { key: 'production', title: 'Производство' },
    numProduction: { key: 'numProduction', title: '№ производства' },
    width: { key: 'width', title: 'Остаток гр.' },
    count: { key: 'count', title: 'Остаток шт.' },
    code: { key: 'code', title: '' },
};
