-- CreateTable
CREATE TABLE "Data" (
    "id" SERIAL NOT NULL,
    "date" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "consignment" TEXT,
    "pp" INTEGER,
    "Personnel" INTEGER,
    "Executor" TEXT,
    "Operation" TEXT NOT NULL,
    "State" TEXT,
    "WorkpieceType" TEXT NOT NULL,
    "Model" TEXT,
    "SizeRange" TEXT,
    "Length" TEXT,
    "channel" DOUBLE PRECISION,
    "grade" TEXT,
    "ColorCype" TEXT,
    "AcceptedGr" DOUBLE PRECISION,
    "IssuedGr" DOUBLE PRECISION,
    "TareWeightGr" DOUBLE PRECISION,
    "Provider" TEXT,
    "Recipient" TEXT,
    "AcceptedPieces" INTEGER,
    "IssuedPieces" INTEGER,
    "NumProduction" INTEGER,
    "WorkingHours" INTEGER,
    "Exercise" TEXT,
    "NumProducts" INTEGER,
    "NumMoving" INTEGER,
    "ParishR" DECIMAL(65,30),
    "ConsumptionR" DECIMAL(65,30),
    "defectR" DECIMAL(65,30),
    "TypeOfProcessing" TEXT,
    "fraction" TEXT,
    "material_group" TEXT,
    "stock" TEXT NOT NULL,
    "NumShipment" INTEGER,
    "shade" TEXT,

    CONSTRAINT "Data_pkey" PRIMARY KEY ("id")
);
