export const data = [
    { id: 1, operation: 'Закупка', activ: true },
    { id: 2, operation: 'Мойка', activ: true },
    { id: 3, operation: 'Номер пр-ва', activ: true },
    { id: 4, operation: 'Сортировка', activ: true },
    { id: 5, operation: 'Клей сырья', activ: true },
    { id: 6, operation: 'Насыщение', activ: true },
    { id: 7, operation: 'Автоклав', activ: true },
    { id: 8, operation: 'Шлифование гравером', activ: true },
    { id: 9, operation: 'Кусанка', activ: true },
    { id: 10, operation: 'Обточка', activ: true },
    { id: 11, operation: 'Калибровка', activ: true },
    { id: 12, operation: 'Докат', activ: true },
    { id: 13, operation: 'Шлифовка', activ: true },
    { id: 14, operation: 'Полировка', activ: true },
    { id: 15, operation: 'Распил', activ: true },
    { id: 16, operation: 'Отгрузка', activ: true },
    { id: 17, operation: 'Перемещение', activ: true },
    { id: 18, operation: 'Смешивание сорт', activ: true },
    { id: 19, operation: 'Сортирока насыщенного', activ: true },
    { id: 20, operation: 'Сортировка автоклав', activ: true },
    { id: 21, operation: 'Сортировка заготовок', activ: true },
    { id: 22, operation: 'Клей заготовок', activ: true },
    { id: 23, operation: 'Распил ИК', activ: true },
    { id: 24, operation: 'Сортировка длин', activ: true },
    { id: 25, operation: 'Смешивание размер', activ: true },
    { id: 26, operation: 'Распил заготовки', activ: true },
    { id: 27, operation: 'Сверление таблетки', activ: true },
    { id: 28, operation: 'Сверление', activ: true },
    { id: 29, operation: 'Шлифование', activ: true },
    { id: 30, operation: 'Сверление водой', activ: true },
    { id: 31, operation: 'Галтовка (грубая)', activ: true },
    { id: 32, operation: 'Термо (лампы)', activ: true },
    { id: 33, operation: 'Термо (печь)', activ: true },
    { id: 34, operation: 'Полировка заготовок', activ: true },
    { id: 35, operation: 'Сортировка элементов', activ: true },
    { id: 36, operation: 'Доработка', activ: true },
    { id: 37, operation: 'Изготовление мин.группы', activ: true },
    { id: 38, operation: 'Сортировка (обрезки)', activ: true },
    { id: 39, operation: 'Смешивание партия', activ: true },
    { id: 40, operation: 'Сборка', activ: true },
    { id: 41, operation: 'Разбор изделий', activ: true },
    { id: 42, operation: 'Смешивание производство', activ: true },
    { id: 43, operation: 'Пересорт', activ: true },
    { id: 44, operation: 'Выбытие', activ: true },
    { id: 45, operation: 'Инвентаризация', activ: true },
    { id: 46, operation: 'Патифон', activ: true },
    { id: 47, operation: 'Шлифование МШ', activ: true },
    { id: 48, operation: 'Клей сырья2', activ: true },
    { id: 49, operation: 'Мойка 2', activ: true },
    { id: 50, operation: 'Галтование', activ: true },
    { id: 51, operation: 'Кастрюля', activ: true },
];
