version: "3.9"
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "13000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-configs:/etc/grafana
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "19090:9090"
    volumes:
      - prom-data:/prometheus
      - prom-configs:/etc/prometheus
  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./volumes/loki/etc:/etc/loki
volumes:
  grafana-data:
  grafana-configs:
  prom-data:
  prom-configs:
