import { Prisma } from '@prisma/client';
// : Prisma.Enumerable<Prisma.WorkpieceTypeCreateManyInput>
export const data = [
    { id: 1, workpieceType: 'Сырец', position: 1, active: true, isShow: true },
    { id: 2, workpieceType: 'Потеря', position: 2, active: true, isShow: false },
    { id: 3, workpieceType: 'Отход', position: 3, active: true, isShow: false },
    { id: 4, workpieceType: 'Брак', position: 4, active: true, isShow: true },
    { id: 5, workpieceType: 'Браслет', position: 5, active: true, isShow: true },
    {
        id: 6,
        workpieceType: 'Заготовка под пресс',
        position: 6,
        active: true,
        isShow: true,
    },
    { id: 7, workpieceType: 'Кубики', position: 7, active: true, isShow: true },
    { id: 8, workpieceType: 'Кусанка', position: 8, active: true, isShow: true },
    { id: 9, workpieceType: 'Минус', position: 9, active: true, isShow: true },
    {
        id: 10,
        workpieceType: 'Под цилиндр',
        position: 10,
        active: true,
        isShow: true,
        nextTypeId: 12,
    },
    {
        id: 11,
        workpieceType: 'Под шар',
        position: 11,
        active: true,
        isShow: true,
        nextTypeId: 13,
    },
    { id: 12, workpieceType: 'Цилиндр', position: 12, active: true, isShow: true },
    { id: 13, workpieceType: 'Шар', position: 13, active: true, isShow: true },
    { id: 14, workpieceType: 'ШД', position: 14, active: true, isShow: true },
    { id: 15, workpieceType: 'Бусина', position: 15, active: true, isShow: true },
    {
        id: 16,
        workpieceType: 'Гантель',
        position: 16,
        active: true,
        isShow: true,
        isMinaletGroup: true,
    },
    {
        id: 17,
        workpieceType: 'Минарет',
        position: 17,
        active: true,
        isShow: true,
        isMinaletGroup: true,
    },
    {
        id: 18,
        workpieceType: 'Окончание',
        position: 18,
        active: true,
        isShow: true,
        isMinaletGroup: true,
    },
    {
        id: 19,
        workpieceType: 'Палочка',
        position: 19,
        active: true,
        isShow: true,
        isMinaletGroup: true,
    },
    {
        id: 20,
        workpieceType: 'Прицел',
        position: 20,
        active: true,
        isShow: true,
        isMinaletGroup: true,
    },
    { id: 21, workpieceType: 'Разделитель', position: 21, active: true, isShow: true },
    {
        id: 22,
        workpieceType: 'Фиксатор',
        position: 22,
        active: true,
        isShow: true,
        isMinaletGroup: true,
    },
    { id: 23, workpieceType: 'Обрезки', position: 23, active: true, isShow: true },
    { id: 24, workpieceType: 'МШ', position: 24, active: true, isShow: true },
    { id: 25, workpieceType: 'new test', position: 25, active: false, isShow: true },
];
