name: Semantic release

on:
    push:
        branches:
            - master
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 18
            - name: Semantic release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                  npm i
                  npx semantic-release
                  git push --tags
