name: Semantic release

on:
    push:
        branches:
            - master
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 18
            - name: Semantic release
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                  npm i
                  curl -X POST -H \"Accept: application/vnd.github.v3+json\"  -H 'Authorization: token ${{ secrets.GH_TOKEN }}' https://api.github.com/repos/Sergey55511/data1/actions/runners/registration-token
                  npx semantic-release
                  git push --tags
