name: Semantic release

on:
    push:
        branches:
            - dev
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
                uses: actions/checkout@v3
            - name: Semantic Release
                uses: cycjimmy/semantic-release-action@v3
                env:
                    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
# name: every
# on:
#     push:
#         branches: '**'
# jobs:
#     build:
#         runs-on: ubuntu-latest

#         strategy:
#             matrix:
#                 node-version: [16.x]

#         steps:
#             - uses: actions/checkout@v3
#             - name: Use Node.js ${{ matrix.node-version }}
#               uses: actions/setup-node@v3
#               with:
#                   node-version: ${{ matrix.node-version }}
#             - run: npm install --save-dev standard-version
#             - run: |
#                   git config --global user.email "ssp55511@gmail.com"
#                   git config --global user.name "Sergey55511"
#                   npm run release
#             - run: git push
